TEST_DATA_PATH="datasets/test_articles.csv"
LB_DATA_PATH="datasets/leaderboard_dataset_revised.csv"
OUTPUT_DIR="output"
TEST_JUDGEMENTS_DATA = "datasets/test_analytics/judgements.jsonl"
TEST_RESULTS_DATA = "datasets/test_analytics/stats.json"