name: Update Leaderboard

on:
  push:
    paths:
      - output/stats_all_LLMs.json

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-action.txt

      # Debug: Confirm working directory & expected files exist
      - name: Debug show working directory and files
        run: |
          echo "PWD: $(pwd)"
          ls -l
          ls -l output
          ls -l img || echo "img folder missing"

      - name: Run update script
        run: python update_readme.py

      # Debug: Show what changed
      - name: Debug show git status and README diff
        run: |
          git status
          git diff README.md || echo "No diff in README.md"
          ls -l img

      - name: Run update script
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md img/
          git diff --quiet && echo "No changes to commit" || (git commit -m "Auto-update leaderboard and plot" && git push)